// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddi_response.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DDIResponse struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DDIResponse) Reset()         { *m = DDIResponse{} }
func (m *DDIResponse) String() string { return proto.CompactTextString(m) }
func (*DDIResponse) ProtoMessage()    {}
func (*DDIResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddi_response_5affde85592c9a49, []int{0}
}
func (m *DDIResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DDIResponse.Unmarshal(m, b)
}
func (m *DDIResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DDIResponse.Marshal(b, m, deterministic)
}
func (dst *DDIResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DDIResponse.Merge(dst, src)
}
func (m *DDIResponse) XXX_Size() int {
	return xxx_messageInfo_DDIResponse.Size(m)
}
func (m *DDIResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DDIResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DDIResponse proto.InternalMessageInfo

func (m *DDIResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func init() {
	proto.RegisterType((*DDIResponse)(nil), "proto.DDIResponse")
}

func init() { proto.RegisterFile("ddi_response.proto", fileDescriptor_ddi_response_5affde85592c9a49) }

var fileDescriptor_ddi_response_5affde85592c9a49 = []byte{
	// 82 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0x49, 0xc9, 0x8c,
	0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x53, 0x4a, 0xea, 0x5c, 0xdc, 0x2e, 0x2e, 0x9e, 0x41, 0x50, 0x39, 0x21, 0x09, 0x2e, 0xf6,
	0xe2, 0xd2, 0xe4, 0xe4, 0xd4, 0xd4, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x18, 0x37,
	0x89, 0x0d, 0xac, 0xde, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x11, 0x0f, 0x09, 0xb4, 0x4c, 0x00,
	0x00, 0x00,
}
