// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.6.1
// source: ddi_response.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DDIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succeed bool `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
}

func (x *DDIResponse) Reset() {
	*x = DDIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ddi_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DDIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DDIResponse) ProtoMessage() {}

func (x *DDIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ddi_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DDIResponse.ProtoReflect.Descriptor instead.
func (*DDIResponse) Descriptor() ([]byte, []int) {
	return file_ddi_response_proto_rawDescGZIP(), []int{0}
}

func (x *DDIResponse) GetSucceed() bool {
	if x != nil {
		return x.Succeed
	}
	return false
}

var File_ddi_response_proto protoreflect.FileDescriptor

var file_ddi_response_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x64, 0x69, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b, 0x44,
	0x44, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ddi_response_proto_rawDescOnce sync.Once
	file_ddi_response_proto_rawDescData = file_ddi_response_proto_rawDesc
)

func file_ddi_response_proto_rawDescGZIP() []byte {
	file_ddi_response_proto_rawDescOnce.Do(func() {
		file_ddi_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_ddi_response_proto_rawDescData)
	})
	return file_ddi_response_proto_rawDescData
}

var file_ddi_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ddi_response_proto_goTypes = []interface{}{
	(*DDIResponse)(nil), // 0: proto.DDIResponse
}
var file_ddi_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ddi_response_proto_init() }
func file_ddi_response_proto_init() {
	if File_ddi_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ddi_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DDIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ddi_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ddi_response_proto_goTypes,
		DependencyIndexes: file_ddi_response_proto_depIdxs,
		MessageInfos:      file_ddi_response_proto_msgTypes,
	}.Build()
	File_ddi_response_proto = out.File
	file_ddi_response_proto_rawDesc = nil
	file_ddi_response_proto_goTypes = nil
	file_ddi_response_proto_depIdxs = nil
}
